### ISSUE TITLE
No more errors, but panel refuses to open via Toggle Panel.

### ISSUE THREAD

**Issue by zhudock** [jccguimaraes/atom-project-viewer#119]
# ISSUE
No more errors, but panel refuses to open.
## Workaround
Disable then Enable the plugin (required each session)

## Steps
With Project Viewer panel closed, attempt to open the panel

## Environment
**Atom**: 1.14.1 ia64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.17 
autocomplete-oracle 0.4.0 
busy 0.7.0 
console-panel 0.2.1 
file-icons 2.0.15 
git-plus 7.2.2 
language-batch 0.4.0 
language-dots 0.0.4 
language-oracle 1.6.2 
language-sqr 0.8.0 
language-vbscript 0.7.0 
line-ending-converter 1.3.2 
linter 1.11.22 
minimap 4.26.8 
pigments 0.39.0 
project-view 0.6.1 
project-viewer 1.0.3 
save-session 0.15.7 
svn 0.0.13 
symbols-tree-view 0.13.2 
synced-sidebar 0.4.3 
tabasco 0.5.0 
tabs-to-spaces 1.0.3 
tortoise-svn 0.5.0 
```

**Comment by jccguimaraes** [comment]
damn :(

**Comment by girlandhercode** [comment]
Related to this ( maybe? ) I just used the command pallet to "Project Viewer Focus Panel" and then tried to use the arrow keys to navigate thru the project list over there. This threw an error I had not encountered before:




[Enter steps to reproduce:]

1. use the command pallet to "Project Viewer Focus Panel"
2. try to use the arrow keys to navigate thru the project list in the focus panel

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\cnmill05\.atom\packages\project-viewer\src\main-view.js:148

TypeError: Cannot read property 'classList' of undefined
    at Array.from.filter.selection (/packages/project-viewer/src/main-view.js:148:20)
    at Array.filter (native)
    at /packages/project-viewer/src/main-view.js:144:61)
    at /packages/project-viewer/src/main.js:144:56)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:41.9.0 command-palette:toggle (input.hidden-input)
 11x -2:39.2.0 core:move-down (input.hidden-input)
     -2:35.1.0 core:move-up (input.hidden-input)
     -2:33.2.0 core:confirm (input.hidden-input)
     -2:33.2.0 project-viewer:openProject (input.hidden-input)
     -2:30 command-palette:toggle (input.hidden-input)
  3x -2:27 core:backspace (input.hidden-input)
     -2:21.7.0 core:confirm (input.hidden-input)
     -2:21.7.0 project-viewer:openProject (input.hidden-input)
     -2:13.9.0 command-palette:toggle (input.hidden-input)
  9x -2:09.3.0 core:move-down (input.hidden-input)
  7x -2:01.8.0 core:move-up (input.hidden-input)
  2x -2:00.3.0 core:move-down (input.hidden-input)
     -1:58.8.0 core:confirm (input.hidden-input)
     -1:58.8.0 project-viewer:focusPanel (input.hidden-input)
  3x -1:57.8.0 core:move-up (project-viewer.pv-has-icons)
```

### Non-Core Packages

```
activate-power-mode-delete 0.6.1 
advanced-open-file 0.16.5 
ask-stack 2.2.0 
atom-beautify 0.29.17 
atom-clock 0.1.3 
atom-jinja2 0.6.0 
atom-material-ui 1.3.9 
atom-mermaid 3.0.0 
atom-monokai 0.10.7 
atom-panda-syntax 0.18.0 
atom-typescript 10.1.14 
AtomicFreckle 0.2.0 
autocomplete-paths 1.0.5 
autoupdate-packages 1.3.1 
browser-plus 0.0.87 
captain-sweetheart 1.0.0 
climate-syntax 5.0.0 
color-picker 2.2.5 
dark-side-of-the-moon-syntax 0.6.8 
dash 1.7.0 
Delete-Whitelines 0.6.3 
duotone-darkpool-syntax 1.1.0 
duotone-darksky 1.1.5 
electron-highlighter-syntax 1.7.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
expose 0.13.0 
file-icons 2.0.15 
file-types 0.5.5 
fold-comments 0.6.0 
git-plus 7.2.2 
github-atom-dark-syntax 0.3.2 
glowing-cursor 0.1.2 
highlight-line 0.12.0 
highlight-selected 0.12.0 
ice-world 0.0.0 
imdone-atom 2.1.18 
indent-guide-improved 1.4.12 
kachun 0.0.0 
keybinding-cheatsheet 0.1.1 
language-ansible 0.2.1 
language-docker 1.1.7 
language-generic-config 1.3.0 
language-gfm-enhanced 0.88.5 
language-ignore 1.5.2 
language-ini 1.17.0 
language-jade 0.7.2 
linter 1.11.22 
linter-docker 0.1.4 
linter-js-yaml 1.2.6 
linter-jshint 3.0.2 
lollypop-unicorn 0.0.0 
markdown-preview-enhanced 0.9.7 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
nebula-syntax 0.4.3 
nebula-ui 0.5.3 
new-era-syntax 1.1.0 
one-outlander-ui 0.3.1 
open-recent 5.0.0 
outlander-syntax 2.0.0 
package-cop 0.2.10 
pigments 0.39.0 
pinned-tabs 0.4.2 
popfizz 0.0.0 
print-atom 0.1.1 
project-manager 3.3.3 
project-viewer 1.0.4 
proton 4.0.2 
proton-kai 0.1.0 
pure-syntax 0.2.1 
quark 0.1.4 
run-time-ui 13.39.0 
section-comment-snippets 2.4.1 
seti-syntax 1.0.1 
seti-ui 1.6.1 
snippet-generator 0.3.2 
spacegray-eighties-ui 1.2.0 
steam-pirate-ui 0.6.1 
sync-settings 0.8.1 
tabasco 0.5.0 
tinacious-design-syntax 1.0.0 
tomorrow 1.0.0 
vector-syntax 0.3.0 
vivid-syntax 2.1.0 
wakatime 6.0.13 
Wild-Cherry 0.9.0 
Zen 0.16.4 
```

**Comment by jccguimaraes** [comment]
@girlandhercode your latest feedback should be also fixed in `1.0.5`

**Comment by girlandhercode** [comment]
@jccguimaraes I am not getting the error message anymore but the sidebar won't open via Packages -> Project Viewer -> Toggle Panel or when using the command pallet to toggle it.  The keybind won't toggle it either.

If i go into the package settings and change "Panel Position" to anything other than what it is currently the panel will show up. This does not survive a restart of atom, however, regardless of whether "Display on startup" or "Remember State" option is chosen.

"Panel visibility interaction state" is also checked, but it changes nothing whether this is checked or not.

Thanks AGAIN for looking into this 🥇

**Comment by CKLFP** [comment]
I've notice that if auto hide is active and from command pallet to "Project Viewer Focus Panel... well the panel won't get visible (auto unhide)... but that is not an issue I'm more than ok with that :) congrats.

**Comment by jccguimaraes** [comment]
@CKLFP working on it ;p

**Comment by zhudock** [comment]
Toggle Panel still doesn't open the panel. I either have to disable\enable the plugin, or change Panel Position to any other value and change it back, on each new session.

Also, regardless of the Panel visibility settings, the panel never opens on startup.

**Comment by jccguimaraes** [comment]
`1.0.6` version?

**Comment by zhudock** [comment]
project-viewer 1.0.6
Atom 1.14.2 x64

Otherwise, all details the same as the initial post above

**Comment by jccguimaraes** [comment]
@zhudock not doubting you, and with so many issues, you confirm this does not work? https://github.com/jccguimaraes/atom-project-viewer/issues/115#issuecomment-279991305

**Comment by zhudock** [comment]
Yep. I have Display on Startup selected in the dropdown and Panel visibility interaction state is checked.

**Comment by girlandhercode** [comment]
1.0.6 is still having a similar issue as before with the panel only being able to be opened by "Enable"/"Disable" toggling or by changing panel position.

If the panel is open and I close and then reopen  atom the panel is not there and I have to follow the same steps to get it to open again.

I also have "Display on startup" and "Panel visibility interaction state" selected/checked.  I don't use "Sidebar auto hiding" so it is unchecked.

**Comment by jccguimaraes** [comment]
i am running out of clues :(

**Comment by CKLFP** [comment]
Hi, have the version 1.0.6 installed, and every thing is ok in here (Windows 10 - updated)... so I suspect is some conflic with another package maybe...
I don't have a a key shortcut but all other methods to toggle are ok.
Good luck.

**Comment by jccguimaraes** [comment]
yeah, next is to pick one by one the packages @girlandhercode listed to see if it matches

**Comment by girlandhercode** [comment]
My installed packages:

activate-power-mode-delete@0.6.1 **(Disabled)**
advanced-open-file@0.16.5
ask-stack@2.2.0
atom-beautify@0.29.17
atom-clock@0.1.3
atom-jinja2@0.6.0
atom-material-ui@1.3.9 **(Active UI Theme)**
atom-monokai@0.10.9
atom-panda-syntax@0.18.0
AtomicFreckle@0.2.0
autocomplete-paths@1.0.5 **(Disabled)**
autoupdate-packages@1.3.1
browser-plus@0.0.87 (Disabled)
captain-sweetheart@1.0.0
climate-syntax@5.0.0
color-picker@2.2.5
colorio@0.1.0 **(Installed after these issues began with Project Viewer)**
dark-side-of-the-moon-syntax@0.6.8
dash@1.7.0
Delete-Whitelines@0.6.3 **(Disabled)**
dracula-theme@2.0.0
duotone-darkpool-syntax@1.1.0
duotone-darksky@1.1.5
electron-highlighter-syntax@1.7.0
emmet@2.4.3
emmet-snippets-compatibility@1.0.6
expose@0.13.0
file-icons@2.0.15
file-types@0.5.5
fold-comments@0.6.0
git-plus@7.3.0 **(Disabled)**
github-atom-dark-syntax@0.3.2
glowing-cursor@0.1.2
highlight-line@0.12.0
highlight-selected@0.12.0
ice-world@0.0.0
imdone-atom@2.1.18
indent-guide-improved@1.4.12
Kachun@0.0.0
keybinding-cheatsheet@0.1.1
language-ansible@0.2.1
language-docker@1.1.7
language-dot@1.6.0
language-generic-config@1.3.0
language-gfm@0.88.0 **(Disabled)**
language-gfm-enhanced@0.89.0
language-ignore@1.5.2
language-ini@1.18.0
language-jade@0.7.2
language-markdown@0.19.1 **(Disabled)**
language-mermaid@0.6.0
language-yaml@0.28.0
linter@1.11.23
linter-docker@0.1.4
linter-js-yaml@1.2.6
linter-jshint@3.0.2
Lollypop-Unicorn@0.0.0
markdown-preview-enhanced@0.9.8
merge-conflicts@1.4.4
minimap@4.26.8
minimap-cursorline@0.2.0
monokai-slate@0.6.0 **(Active Syntax theme)**
nebula-syntax@0.4.3
nebula-ui@0.5.3
new-era-syntax@1.1.0
newton-dark-syntax@1.1.7
one-outlander-ui@0.3.1
open-recent@5.0.0
outlander-syntax@2.0.0
package-cop@0.2.10
pigments@0.39.0
pinned-tabs@0.4.2
Popfizz@0.0.0
print-atom@0.1.1
project-manager@3.3.3 **(Disabled)**
project-viewer@1.0.6
proton@4.0.2
proton-kai@0.1.0
pure-syntax@0.2.1
quark@0.1.4
run-time-ui@13.39.0
section-comment-snippets@2.4.1
seti-ui@1.6.1
snippet-generator@0.3.2
spacegray-eighties-ui@1.2.0
steam-pirate-ui@0.6.1
sync-settings@0.8.1
tabasco@0.5.0
tinacious-design-syntax@1.0.0
tomorrow@1.0.0
vector-syntax@0.3.0
vivid-syntax@2.1.0
wakatime@6.0.13
Wild-Cherry@0.9.0
wrap-guide@0.39.1 **(Disabled)**

**Comment by girlandhercode** [comment]
I disabled tobasco (not needed anymore since you can natively drag tabs in atom now - and its throwing an error regardless), git-plus, and merge-conflicts since we have overlap with those.  I can now successfully toggle via the shortcut keys or the command pallet.  I have since re-enabled git-plus and merge conflicts and I am still able to toggle successfully. Project Viewer now also remembers state correctly and when restarting atom the panel is there.

I'm sorry this turned out to be a package conflict!! Thank you @jccguimaraes for all of the help and for creating/maintaining this package!! Thanks @CKLFP for reporting in that yours was working!!

**Comment by zhudock** [comment]
Confirmed the issue with tabasco. After disabling that plugin, all is working great. Thanks again for all of your efforts!

**Comment by jccguimaraes** [comment]
thank you all for the effort in sorting this out @zhudock, @girlandhercode, @CKLFP. Although the source of the problem has been found, i will do in time, investigate why, and try to make it both work simultaneously.

Thank you all!
